/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FFGui;


/*
 * Made by the wonderful mind of Dhwani Shah :D 
 */

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

//import javafx.scene.media.MediaPlayer;

/**
 *
 * @author 220042833
 */
public class FamilyFuedFrame extends javax.swing.JFrame {

    /**
     * Creates new form FamilyFuedFrame
     */
    public FamilyFuedFrame() {
        initComponents();
        PlayTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sr1_1 = new javax.swing.JToggleButton();
        sr1_q = new javax.swing.JLabel();
        sr1_2 = new javax.swing.JToggleButton();
        sr1_3 = new javax.swing.JToggleButton();
        sr1_5 = new javax.swing.JToggleButton();
        sr1_6 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        sr1_4 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        wb_1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sr1_q1 = new javax.swing.JLabel();
        sr2_1 = new javax.swing.JToggleButton();
        sr2_2 = new javax.swing.JToggleButton();
        sr2_3 = new javax.swing.JToggleButton();
        sr2_4 = new javax.swing.JToggleButton();
        sr2_5 = new javax.swing.JToggleButton();
        sr1_12 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        wb_2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sr1_q2 = new javax.swing.JLabel();
        sr3_1 = new javax.swing.JToggleButton();
        sr3_2 = new javax.swing.JToggleButton();
        sr3_3 = new javax.swing.JToggleButton();
        sr3_4 = new javax.swing.JToggleButton();
        sr3_5 = new javax.swing.JToggleButton();
        sr3_6 = new javax.swing.JToggleButton();
        sr3_7 = new javax.swing.JToggleButton();
        sr3_8 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        wb_3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        sr1_q3 = new javax.swing.JLabel();
        sr4_1 = new javax.swing.JToggleButton();
        sr4_2 = new javax.swing.JToggleButton();
        sr4_3 = new javax.swing.JToggleButton();
        sr4_4 = new javax.swing.JToggleButton();
        sr4_5 = new javax.swing.JToggleButton();
        wb_4 = new javax.swing.JButton();
        sr4_10 = new javax.swing.JToggleButton();
        sr4_9 = new javax.swing.JToggleButton();
        sr4_8 = new javax.swing.JToggleButton();
        sr4_7 = new javax.swing.JToggleButton();
        sr4_6 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        sr1_q4 = new javax.swing.JLabel();
        sr5_1 = new javax.swing.JToggleButton();
        sr5_2 = new javax.swing.JToggleButton();
        sr5_3 = new javax.swing.JToggleButton();
        sr5_4 = new javax.swing.JToggleButton();
        sr5_5 = new javax.swing.JToggleButton();
        wb_5 = new javax.swing.JButton();
        sr4_16 = new javax.swing.JToggleButton();
        sr4_17 = new javax.swing.JToggleButton();
        sr5_8 = new javax.swing.JToggleButton();
        sr5_7 = new javax.swing.JToggleButton();
        sr5_6 = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        sr1_q5 = new javax.swing.JLabel();
        sr6_1 = new javax.swing.JToggleButton();
        sr6_2 = new javax.swing.JToggleButton();
        sr6_3 = new javax.swing.JToggleButton();
        sr6_4 = new javax.swing.JToggleButton();
        sr6_5 = new javax.swing.JToggleButton();
        wb_6 = new javax.swing.JButton();
        sr4_18 = new javax.swing.JToggleButton();
        sr4_19 = new javax.swing.JToggleButton();
        sr5_14 = new javax.swing.JToggleButton();
        sr6_7 = new javax.swing.JToggleButton();
        sr6_6 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        t1_score = new javax.swing.JTextField();
        t2_score = new javax.swing.JTextField();
        t3_score = new javax.swing.JTextField();
        t1_addscore = new javax.swing.JTextField();
        t2_addscore = new javax.swing.JTextField();
        t3_addscore = new javax.swing.JTextField();
        team1_butt = new javax.swing.JButton();
        team2_butt = new javax.swing.JButton();
        team3_butt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Family Fued!!!");
        setResizable(false);

        jButton1.setText("Stop Theme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Welcome!", jPanel4);

        sr1_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_1.setText("(1)");
        sr1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_1ActionPerformed(evt);
            }
        });

        sr1_q.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q.setText("Name something you use often, that's always breaking down");

        sr1_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_2.setText("(2)");
        sr1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_2ActionPerformed(evt);
            }
        });

        sr1_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_3.setText("(3)");
        sr1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_3ActionPerformed(evt);
            }
        });

        sr1_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_5.setText("(5)");
        sr1_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_5ActionPerformed(evt);
            }
        });

        sr1_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_6.setText("(6)");
        sr1_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_6ActionPerformed(evt);
            }
        });

        jToggleButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton6.setEnabled(false);

        sr1_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_4.setText("(4)");
        sr1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_4ActionPerformed(evt);
            }
        });

        jToggleButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton8.setEnabled(false);

        jToggleButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton9.setEnabled(false);

        jToggleButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton10.setEnabled(false);

        wb_1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_1.setForeground(new java.awt.Color(255, 0, 0));
        wb_1.setText("X");
        wb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wb_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sr1_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr1_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr1_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr1_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr1_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_1)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Single Round #1", jPanel1);

        sr1_q1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q1.setText("Name something that lets off steam");

        sr2_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr2_1.setText("(1)");
        sr2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2_1ActionPerformed(evt);
            }
        });

        sr2_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr2_2.setText("(2)");
        sr2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2_2ActionPerformed(evt);
            }
        });

        sr2_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr2_3.setText("(3)");
        sr2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2_3ActionPerformed(evt);
            }
        });

        sr2_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr2_4.setText("(4)");
        sr2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2_4ActionPerformed(evt);
            }
        });

        sr2_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr2_5.setText("(5)");
        sr2_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr2_5ActionPerformed(evt);
            }
        });

        sr1_12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr1_12.setEnabled(false);
        sr1_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr1_12ActionPerformed(evt);
            }
        });

        jToggleButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton7.setEnabled(false);

        jToggleButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton11.setEnabled(false);

        jToggleButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton12.setEnabled(false);

        jToggleButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton13.setEnabled(false);

        wb_2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_2.setForeground(new java.awt.Color(255, 0, 0));
        wb_2.setText("X");
        wb_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wb_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr2_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr2_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jToggleButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr1_12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr1_12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_2)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Single Round #2", jPanel2);

        sr1_q2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q2.setText("Name a kind of candy that comes in different colors");

        sr3_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_1.setText("(1)");
        sr3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_1ActionPerformed(evt);
            }
        });

        sr3_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_2.setText("(2)");
        sr3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_2ActionPerformed(evt);
            }
        });

        sr3_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_3.setText("(3)");
        sr3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_3ActionPerformed(evt);
            }
        });

        sr3_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_4.setText("(4)");
        sr3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_4ActionPerformed(evt);
            }
        });

        sr3_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_5.setText("(5)");
        sr3_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_5ActionPerformed(evt);
            }
        });

        sr3_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_6.setText("(6)");
        sr3_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_6ActionPerformed(evt);
            }
        });

        sr3_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_7.setText("(7)");
        sr3_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_7ActionPerformed(evt);
            }
        });

        sr3_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr3_8.setText("(8)");
        sr3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr3_8ActionPerformed(evt);
            }
        });

        jToggleButton16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton16.setEnabled(false);

        jToggleButton17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton17.setEnabled(false);

        wb_3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_3.setForeground(new java.awt.Color(255, 0, 0));
        wb_3.setText("X");
        wb_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr3_2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr3_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr3_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr3_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr3_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr3_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr3_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr3_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(wb_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_3)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Single Round #3", jPanel3);

        sr1_q3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q3.setText("Name a city that comes to mind when you think of spy movies");

        sr4_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_1.setText("(1)");
        sr4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_1ActionPerformed(evt);
            }
        });

        sr4_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_2.setText("(2)");
        sr4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_2ActionPerformed(evt);
            }
        });

        sr4_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_3.setText("(3)");
        sr4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_3ActionPerformed(evt);
            }
        });

        sr4_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_4.setText("(4)");
        sr4_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_4ActionPerformed(evt);
            }
        });

        sr4_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_5.setText("(5)");
        sr4_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_5ActionPerformed(evt);
            }
        });

        wb_4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_4.setForeground(new java.awt.Color(255, 0, 0));
        wb_4.setText("X");
        wb_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_4ActionPerformed(evt);
            }
        });

        sr4_10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_10.setEnabled(false);

        sr4_9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_9.setEnabled(false);

        sr4_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_8.setText("(8)");
        sr4_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_8ActionPerformed(evt);
            }
        });

        sr4_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_7.setText("(7)");
        sr4_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_7ActionPerformed(evt);
            }
        });

        sr4_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_6.setText("(6)");
        sr4_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr4_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q3, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sr4_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr4_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr4_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr4_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(wb_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_4)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Double Round #1", jPanel5);

        sr1_q4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q4.setText(" Name an activity that's so boring it makes you sleepy");

        sr5_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_1.setText("(1)");
        sr5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_1ActionPerformed(evt);
            }
        });

        sr5_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_2.setText("(2)");
        sr5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_2ActionPerformed(evt);
            }
        });

        sr5_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_3.setText("(3)");
        sr5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_3ActionPerformed(evt);
            }
        });

        sr5_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_4.setText("(4)");
        sr5_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_4ActionPerformed(evt);
            }
        });

        sr5_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_5.setText("(5)");
        sr5_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_5ActionPerformed(evt);
            }
        });

        wb_5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_5.setForeground(new java.awt.Color(255, 0, 0));
        wb_5.setText("X");
        wb_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_5ActionPerformed(evt);
            }
        });

        sr4_16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_16.setEnabled(false);

        sr4_17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_17.setEnabled(false);

        sr5_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_8.setEnabled(false);
        sr5_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_8ActionPerformed(evt);
            }
        });

        sr5_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_7.setText("(7)");
        sr5_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_7ActionPerformed(evt);
            }
        });

        sr5_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_6.setText("(6)");
        sr5_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q4, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr5_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr5_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr4_17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr5_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(wb_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q4)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sr4_16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_5)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Double Round #2", jPanel6);

        sr1_q5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        sr1_q5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sr1_q5.setText("Name something a little kid might tell you about Santa Claus");

        sr6_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_1.setText("(1)");
        sr6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_1ActionPerformed(evt);
            }
        });

        sr6_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_2.setText("(2)");
        sr6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_2ActionPerformed(evt);
            }
        });

        sr6_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_3.setText("(3)");
        sr6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_3ActionPerformed(evt);
            }
        });

        sr6_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_4.setText("(4)");
        sr6_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_4ActionPerformed(evt);
            }
        });

        sr6_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_5.setText("(5)");
        sr6_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_5ActionPerformed(evt);
            }
        });

        wb_6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wb_6.setForeground(new java.awt.Color(255, 0, 0));
        wb_6.setText("X");
        wb_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wb_6ActionPerformed(evt);
            }
        });

        sr4_18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_18.setEnabled(false);

        sr4_19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr4_19.setEnabled(false);

        sr5_14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr5_14.setEnabled(false);
        sr5_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr5_14ActionPerformed(evt);
            }
        });

        sr6_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_7.setText("(7)");
        sr6_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_7ActionPerformed(evt);
            }
        });

        sr6_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sr6_6.setText("(6)");
        sr6_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sr6_6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sr1_q5, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr6_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr6_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr6_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr6_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr6_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sr4_19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr5_14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr6_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(sr6_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sr4_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(wb_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sr1_q5)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr5_14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sr6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr4_19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sr4_18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sr6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(wb_6)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Triple Round", jPanel7);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Family Feud!!!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel2.setText("Team 1");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel3.setText("Team 2");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel4.setText("Team 3");

        t1_score.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t1_score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1_score.setText("0");

        t2_score.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t2_score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2_score.setText("0");

        t3_score.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t3_score.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3_score.setText("0");

        t1_addscore.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t1_addscore.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t2_addscore.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t2_addscore.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t3_addscore.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        t3_addscore.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        team1_butt.setText("+");
        team1_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1_buttActionPerformed(evt);
            }
        });

        team2_butt.setText("+");
        team2_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2_buttActionPerformed(evt);
            }
        });

        team3_butt.setText("+");
        team3_butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team3_buttActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 2, 12)); // NOI18N
        jLabel5.setText("Made by Dhwani Shah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane3))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t1_addscore, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t1_score, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(team1_butt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t2_score, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t2_addscore, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(team2_butt)))
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t3_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t3_addscore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(team3_butt)
                                .addGap(7, 7, 7))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1_score, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2_score, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3_score, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(team1_butt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t1_addscore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t2_addscore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t3_addscore, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(team2_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(team3_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private AudioInputStream clipNameAIS;
    private Clip clipNameClip;
    
    private void PlayCorrectSound() {
        try
        {
        clipNameAIS = AudioSystem.getAudioInputStream(getClass().getResourceAsStream("FamilyFeudBell.wav"));
        clipNameClip = AudioSystem.getClip();
        clipNameClip.open(clipNameAIS);
        } catch(Exception e){System.out.println("Failure to load sound"); }
        //Action where .wav is played
        clipNameClip.setFramePosition(0);
        clipNameClip.start();
    }
    
    private void PlayIncorrectSound() {
        try
        {
        clipNameAIS = AudioSystem.getAudioInputStream(getClass().getResourceAsStream("FamilyFeudBuzzer.wav"));
        clipNameClip = AudioSystem.getClip();
        clipNameClip.open(clipNameAIS);
        } catch(Exception e){System.out.println("Failure to load sound"); }
        //Action where .wav is played
        clipNameClip.setFramePosition(0);
        clipNameClip.start();
    }
    
    private void PlayTheme() {
        try
        {
        clipNameAIS = AudioSystem.getAudioInputStream(getClass().getResourceAsStream("FamilyFeudTheme.wav"));
        clipNameClip = AudioSystem.getClip();
        clipNameClip.open(clipNameAIS);
        } catch(Exception e){System.out.println("Failure to load sound"); }
        //Action where .wav is played
        clipNameClip.setFramePosition(0);
        clipNameClip.start();
    }
    
    private void StopAllSound() {
        clipNameClip.stop();
    }
    
    private void sr1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_1ActionPerformed
        sr1_1.setText("Car [56]");  
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_1ActionPerformed

    private void sr1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_2ActionPerformed
        sr1_2.setText("Lawn Mower [15]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_2ActionPerformed

    private void sr1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_3ActionPerformed
        sr1_3.setText("Vacuum Cleaner [5]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_3ActionPerformed

    private void sr1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_4ActionPerformed
        sr1_4.setText("Copier [4]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_4ActionPerformed

    private void sr1_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_5ActionPerformed
        sr1_5.setText("Dishwasher [4]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_5ActionPerformed

    private void sr1_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_6ActionPerformed
        sr1_6.setText("TV [3]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr1_6ActionPerformed

    private void sr2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2_1ActionPerformed
        sr2_1.setText("Teakettle [51]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr2_1ActionPerformed

    private void sr2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2_2ActionPerformed
        sr2_2.setText("Clothes Iron [17]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr2_2ActionPerformed

    private void sr2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2_3ActionPerformed
        sr2_3.setText("Train [12]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr2_3ActionPerformed

    private void sr2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2_4ActionPerformed
        sr2_4.setText("Pressure Cooker [8]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr2_4ActionPerformed

    private void sr2_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr2_5ActionPerformed
        sr2_5.setText("Steam Engine [4]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr2_5ActionPerformed

    private void sr1_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr1_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr1_12ActionPerformed

    private void sr3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_1ActionPerformed
        sr3_1.setText("Lifesavers [23]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_1ActionPerformed

    private void sr3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_2ActionPerformed
        sr3_2.setText("M & M [23]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_2ActionPerformed

    private void sr3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_3ActionPerformed
        sr3_3.setText("Taffy [18]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_3ActionPerformed

    private void sr3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_4ActionPerformed
        sr3_4.setText("Jellybeans [9]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_4ActionPerformed

    private void sr3_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_5ActionPerformed
        sr3_5.setText("Lollipops [7]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_5ActionPerformed

    private void sr3_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_6ActionPerformed
        sr3_6.setText("Mints [3]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_6ActionPerformed

    private void sr3_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_7ActionPerformed
        sr3_7.setText("Skittles [3]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_7ActionPerformed

    private void sr3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr3_8ActionPerformed
        sr3_8.setText("Starburst [3]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr3_8ActionPerformed

    private void wb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_1ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_1ActionPerformed

    private void wb_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_2ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_2ActionPerformed

    private void wb_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_3ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StopAllSound();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sr4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_1ActionPerformed
        sr4_1.setText("London [33 -> 66]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_1ActionPerformed

    private void sr4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_2ActionPerformed
        sr4_2.setText("Paris [19 -> 38]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_2ActionPerformed

    private void sr4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_3ActionPerformed
        sr4_3.setText("New York City [12 -> 24]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_3ActionPerformed

    private void sr4_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_4ActionPerformed
        sr4_4.setText("Moscow [6 -> 12]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_4ActionPerformed

    private void sr4_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_5ActionPerformed
        sr4_5.setText("Washington DC [6 -> 12]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_5ActionPerformed

    private void wb_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_4ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_4ActionPerformed

    private void sr4_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_8ActionPerformed
        sr4_8.setText("San Francisco [3 -> 6]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_8ActionPerformed

    private void sr4_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_7ActionPerformed
        sr4_7.setText("Rome [3 -> 6]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_7ActionPerformed

    private void sr4_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr4_6ActionPerformed
        sr4_6.setText("Berlin [5 -> 10]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr4_6ActionPerformed

    private void sr5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_1ActionPerformed
        sr5_1.setText("Reading [23 -> 46]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_1ActionPerformed

    private void sr5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_2ActionPerformed
        sr5_2.setText("Watching TV [19 -> 38]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_2ActionPerformed

    private void sr5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_3ActionPerformed
        sr5_3.setText("Watching Sports [14 -> 28]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_3ActionPerformed

    private void sr5_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_4ActionPerformed
        sr5_4.setText("Lecture [10 -> 20]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_4ActionPerformed

    private void sr5_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_5ActionPerformed
        sr5_5.setText("Studying [9 -> 18]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_5ActionPerformed

    private void wb_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_5ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_5ActionPerformed

    private void sr5_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr5_8ActionPerformed

    private void sr5_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_7ActionPerformed
        sr5_7.setText("Sunbathing [3 -> 6]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_7ActionPerformed

    private void sr5_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_6ActionPerformed
        sr5_6.setText("Driving [6 -> 12]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr5_6ActionPerformed

    private void team1_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1_buttActionPerformed
        int currentScore = Integer.parseInt(t1_score.getText());
        int scoreToAdd= Integer.parseInt(t1_addscore.getText());
        t1_score.setText(Integer.toString(currentScore + scoreToAdd));
        t1_addscore.setText("");
    }//GEN-LAST:event_team1_buttActionPerformed

    private void team2_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2_buttActionPerformed
        int currentScore = Integer.parseInt(t2_score.getText());
        int scoreToAdd= Integer.parseInt(t2_addscore.getText());
        t2_score.setText(Integer.toString(currentScore + scoreToAdd));
        t2_addscore.setText("");
    }//GEN-LAST:event_team2_buttActionPerformed

    private void team3_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team3_buttActionPerformed
        int currentScore = Integer.parseInt(t3_score.getText());
        int scoreToAdd= Integer.parseInt(t3_addscore.getText());
        t3_score.setText(Integer.toString(currentScore + scoreToAdd));
        t3_addscore.setText("");
    }//GEN-LAST:event_team3_buttActionPerformed

    private void sr6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_1ActionPerformed
        sr6_1.setText("He is Plump [33 -> 99]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_1ActionPerformed

    private void sr6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_2ActionPerformed
        sr6_2.setText("Is Jolly [14 -> 42]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_2ActionPerformed

    private void sr6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_3ActionPerformed
        sr6_3.setText("Has a Beard [14 -> 42]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_3ActionPerformed

    private void sr6_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_4ActionPerformed
        sr6_4.setText("Wears a red suit [12 -> 36]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_4ActionPerformed

    private void sr6_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_5ActionPerformed
        sr6_5.setText("He's Real [11 -> 33]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_5ActionPerformed

    private void wb_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wb_6ActionPerformed
        PlayIncorrectSound();
    }//GEN-LAST:event_wb_6ActionPerformed

    private void sr5_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr5_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sr5_14ActionPerformed

    private void sr6_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_7ActionPerformed
        sr6_7.setText("Lives at north pole [6 -> 18]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_7ActionPerformed

    private void sr6_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sr6_6ActionPerformed
        sr6_6.setText("Brings Presents [9 -> 27]");
        PlayCorrectSound();
    }//GEN-LAST:event_sr6_6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyFuedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyFuedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyFuedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyFuedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyFuedFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToggleButton sr1_1;
    private javax.swing.JToggleButton sr1_12;
    private javax.swing.JToggleButton sr1_2;
    private javax.swing.JToggleButton sr1_3;
    private javax.swing.JToggleButton sr1_4;
    private javax.swing.JToggleButton sr1_5;
    private javax.swing.JToggleButton sr1_6;
    private javax.swing.JLabel sr1_q;
    private javax.swing.JLabel sr1_q1;
    private javax.swing.JLabel sr1_q2;
    private javax.swing.JLabel sr1_q3;
    private javax.swing.JLabel sr1_q4;
    private javax.swing.JLabel sr1_q5;
    private javax.swing.JToggleButton sr2_1;
    private javax.swing.JToggleButton sr2_2;
    private javax.swing.JToggleButton sr2_3;
    private javax.swing.JToggleButton sr2_4;
    private javax.swing.JToggleButton sr2_5;
    private javax.swing.JToggleButton sr3_1;
    private javax.swing.JToggleButton sr3_2;
    private javax.swing.JToggleButton sr3_3;
    private javax.swing.JToggleButton sr3_4;
    private javax.swing.JToggleButton sr3_5;
    private javax.swing.JToggleButton sr3_6;
    private javax.swing.JToggleButton sr3_7;
    private javax.swing.JToggleButton sr3_8;
    private javax.swing.JToggleButton sr4_1;
    private javax.swing.JToggleButton sr4_10;
    private javax.swing.JToggleButton sr4_16;
    private javax.swing.JToggleButton sr4_17;
    private javax.swing.JToggleButton sr4_18;
    private javax.swing.JToggleButton sr4_19;
    private javax.swing.JToggleButton sr4_2;
    private javax.swing.JToggleButton sr4_3;
    private javax.swing.JToggleButton sr4_4;
    private javax.swing.JToggleButton sr4_5;
    private javax.swing.JToggleButton sr4_6;
    private javax.swing.JToggleButton sr4_7;
    private javax.swing.JToggleButton sr4_8;
    private javax.swing.JToggleButton sr4_9;
    private javax.swing.JToggleButton sr5_1;
    private javax.swing.JToggleButton sr5_14;
    private javax.swing.JToggleButton sr5_2;
    private javax.swing.JToggleButton sr5_3;
    private javax.swing.JToggleButton sr5_4;
    private javax.swing.JToggleButton sr5_5;
    private javax.swing.JToggleButton sr5_6;
    private javax.swing.JToggleButton sr5_7;
    private javax.swing.JToggleButton sr5_8;
    private javax.swing.JToggleButton sr6_1;
    private javax.swing.JToggleButton sr6_2;
    private javax.swing.JToggleButton sr6_3;
    private javax.swing.JToggleButton sr6_4;
    private javax.swing.JToggleButton sr6_5;
    private javax.swing.JToggleButton sr6_6;
    private javax.swing.JToggleButton sr6_7;
    private javax.swing.JTextField t1_addscore;
    private javax.swing.JTextField t1_score;
    private javax.swing.JTextField t2_addscore;
    private javax.swing.JTextField t2_score;
    private javax.swing.JTextField t3_addscore;
    private javax.swing.JTextField t3_score;
    private javax.swing.JButton team1_butt;
    private javax.swing.JButton team2_butt;
    private javax.swing.JButton team3_butt;
    private javax.swing.JButton wb_1;
    private javax.swing.JButton wb_2;
    private javax.swing.JButton wb_3;
    private javax.swing.JButton wb_4;
    private javax.swing.JButton wb_5;
    private javax.swing.JButton wb_6;
    // End of variables declaration//GEN-END:variables
}
